#!/usr/bin/env bash
set -euo pipefail

RELAY_PLS_REPO_BASE="${RELAY_PLS_REPO_BASE:-gcr.io/nebula-235818}"
RELAY_PLS_RELEASE_REPOS=( "${RELAY_PLS_REPO_BASE}/relay-pls")

release_docker_images() {
    if [ "${NO_DOCKER_PUSH}" != "yes" ]; then
        gcloud auth configure-docker || fail "gcloud authentication was not configured correctly"

        for REPO in "${RELAY_PLS_RELEASE_REPOS[@]}"; do
            docker push "${REPO}:${VERSION}" || fail "failed to push to the docker repository"
            if [ "${RELAY_PLS_RELEASE_LATEST}" = "true" ]; then
                docker tag "${REPO}:${VERSION}" "${REPO}"
                docker push "${REPO}" || fail "failed to push to the docker repository"
            fi
        done
    else
        echo "docker images were created, but not pushed"
    fi
}

release_docker_images
